name:                IF708-KV
version:             0.1.0.0
github:              "githubuser/IF708-KV"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/IF708-KV#readme>

dependencies:
- aeson >= 1.3.1.1 && < 2
- base >= 4.7 && < 5
- containers >= 0.5.11.0 && < 1
- http-api-data >= 0.3.5 && < 1
- http-client >= 0.5.14 && < 1
- http-types >= 0.12.2 && < 1
- mtl >= 2.2.2 && < 3
- servant >= 0.9.1.1 && < 1
- servant-client >= 0.9.1.1 && < 1
- servant-server >= 0.9.1.1 && < 1
- text >= 1.2.3.1 && < 2
- warp >= 3.2.25 && < 4

library:
  source-dirs: src

executables:
  IF708-KV-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IF708-KV

tests:
  IF708-KV-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IF708-KV
